builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
   
    flags:
      - -trimpath
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: cloudlens
    homepage: https://github.com/one2nc/cloudlens
    tap:
      owner: one2nc
      name: homebrew-cloudlens
    commit_author:
      name: one2nc
      email: chinmay@one2n.in

checksum:
  name_template: 'checksums.txt'
