version: '3'
services:
  localstack:
    container_name: cloudlens-localstack
    image: localstack/localstack:1.3.1
    environment:
      - SERVICES=s3,ec2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localhost
    ports:
      - "4566:4566"
    volumes:
      - "./data:/tmp/localstack/data"
    networks:
        - default
networks:
    default: